events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    # Разрешаем Nginx пропускать запросы до 50 МБ, чтобы Python успел ответить человеческой ошибкой
    client_max_body_size 50M;

    server {
        listen 80;
        server_name localhost;

        # 1. Точные совпадения для бэкенда Python.
        # Каждому известному пути — самый высокий приоритет. Принудительно гоним их в Python.
        location ~ ^/(list|upload|delete|list/|delete/|)$ {
            proxy_pass http://backend:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # 2. Прямая раздача картинок через Nginx.
        # Начинается строго с /images/, берется из папки тома.
        location /images/ {
            root /usr/share/nginx/html;
            try_files $uri =404;
            add_header Cache-Control "public, max-age=86400"; # кэшируем на 24 часа
        }
    }
}